# Generated by Django 4.0 on 2022-02-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=510)),
                ('full_description', models.CharField(max_length=1024)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
